spring:
  application:
    name: pedido-service

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

mensaje:
  texto: Configuración obtenida desde Config Server para Pedido Service

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      clienteService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      productoService:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      clienteRetry:
        maxAttempts: 3
        waitDuration: 2s
  bulkhead:
    instances:
      productoBulkhead:
        maxConcurrentCalls: 2
        maxWaitDuration: 1s
